### ISSUE TITLE
Missing port variable

### ISSUE THREAD

**Issue by patricksegantine** [huseyinbabal/microservices#1]
https://github.com/huseyinbabal/microservices/blob/220857c10543a57b6176bb255cfb94826f80dc22/order/internal/adapters/grpc/server.go#L40

**Comment by huseyinbabal** [comment]
> rpc on port ")

@patricksegantine thanks :) I  already realized this and new changes are coming up for the new chapters, I will be handling that. Appreciate your help 🙏

**Comment by huseyinbabal** [comment]
This is now fixed in main branch, thanks
